### ISSUE TITLE
无法上传进行识别

### ISSUE THREAD

**Issue by sueRimn** [SuperBinlin/xunfeiwebapi#1]
我使用websocket，在前台使用`ws.send(blob)`传给了服务器，不知道如何进行语音识别的呢

**Comment by SuperBinlin** [comment]
这是一个纯前端调用讯飞语音识别服务的demo 所以需要一些插件来防止跨域 在实际产品开发和应用中 需要将音频base64发给后端 后端拿base64调讯飞的语音识别服务
